Se vor folosi type annotations pentru variabile, parametrii tuturor funcțiilor, tipuri de retur. Se vor folosi docstrings pentru toate funcțiile. Neîndeplinirea acestei cerințe duce la înjumătățirea punctajului pentru exercițiul în cauză.  

Se acordă doua puncte din oficiu. Fișierul va fi denumit tema3_ia_nume_prenume.ipynb. Verificați înainte de trimitere faptul ca execuția celulelor de sus în jos funcționează corespunzător. Aserțiunile sunt obligatoriu a fi indeplinite. Suplimentar, puteti face verificari si pentru alte valori.

1. (1p) Pentru un vector de numere, care sunt toate pozitiile pe care apare valoarea minima?
Folositi functii NumPy.

In [1]:
import numpy as np

def get_all_positions_of_min(arr: np.ndarray) -> np.array:
    """returns a tuple of all positions of the min value in the array.
    weirdly np.where() also generates the datatype so i have to only use the index 0 of the function
    # yes"""
    minimum = np.min(arr)
    positions_of_min= (np.where(arr == minimum)[0])
    return positions_of_min

if __name__ == '__main__':
    v = np.array([1, 2, 3, 4, 4, 3, 1] * 2, dtype=np.float32)  #array*2 is like string*2. it doubles it
    positions_of_min= get_all_positions_of_min(v)
    print(positions_of_min)
    
    assert np.all(positions_of_min == [ 0,  6,  7, 13])

[ 0  6  7 13]


2. (1p) Construiti o functie care, primind o matrice, determina pe ce pozitii (linii, coloane) se afla valorile in intervalele [a, b] sau [c, d] date ca parametri. Functia va returna un tuplu de doi vectori: primul e cu indicii de linie, al doilea cu indicii de coloana unde se afla elementele cautate.

Exemplu:

In [2]:
from typing import List
import numpy as np

def pos_values(matrix: np.ndarray, a:int, b:int, c:int, d:int) ->tuple:
    """instead of having two loops, i looped through a tuple made of both a,b and c,d. for every element in the matrix 
    check if it satifies the condition of being in the range of a,b and c,d. if yes -> add it to the lists accordingly"""
    print(matrix)
    rows: List=[]
    columns: List=[]
    two_intervals: tuple[tuple]=((a, b), (c, d))
    for left_limit, right_limit in two_intervals:
        for(indexes, value) in np.ndenumerate(matrix):
            if value >= left_limit and value <= right_limit:
                rows.append(indexes[0])
                columns.append(indexes[1])
    print("rows:", rows)
    print("columns:", columns, '\n')
    return (rows, columns)

if __name__ == '__main__':
    mat = np.arange(12).reshape(3, 4)
    rows, cols = pos_values(mat, 2, 4, 6, 8)
    assert np.all(rows == [0, 0, 1, 1, 1, 2])
    assert np.all(cols == [2, 3, 0, 2, 3, 0])

    mat = -np.arange(12).reshape(3, 4)
    rows, cols = pos_values(mat, 2, 4, 6, 8)
    assert np.all(rows == [])
    assert np.all(cols == [])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
rows: [0, 0, 1, 1, 1, 2]
columns: [2, 3, 0, 2, 3, 0] 

[[  0  -1  -2  -3]
 [ -4  -5  -6  -7]
 [ -8  -9 -10 -11]]
rows: []
columns: [] 



3. (1p) Se da un vector cu numere intregi nenule. Sa se determine toti indicii `i` unde urmeaza o schimbare de semn. Codul se va scrie intr-o functie adnotata.

Exemplu: 
```python
v = [1, 2, -1, 2, 3, -1, 3, -10, -10, -10]
```
Trebuie sa rezulte vectorul de indici: `[1, 2, 4, 5, 6]`.

De luat in considerare ca:
1. Magnitudinea valorilor nu conteaza, doar semnele lor
1. Functia `where` gaseste indicii unde anumite proprietati sunt indeplinite

In [3]:
import numpy as np

def jumping(v: np.array)->np.array:
    """function to find the indexes where a change of sign happens AFTER the said index\n
    -->use np.diff() to get the difference between the elem of the array like this: \n
    array of signs:    [+1  +1  -1  +1  +1  -1  +1  -1  -1  -1] -> changes happen AFTER the indexes: 1, 2, 4, 5, 6\n
    using np.diff on it: [+0  -2  +2  +0  -2  +2  -2  +0  +0] -> changes happen AT the indexes: 1, 2, 4, 5, 6 (marked by non-zero elements)\n
    -->np.where() goes through the array and returns the indexes where the condition given is true"""
    assert np.all( v != 0), 'All values should be non-zero'
    i_list_of_sign_changes: List[int]=np.diff(np.sign(v))
    i_list_of_sign_changes=np.where(i_list_of_sign_changes != 0)[0]
    return i_list_of_sign_changes

if __name__ == '__main__':
    # test 1
    v: np.array = np.array([1, 2, -1, 2, 3, -1, 3, -10, -10, -10])
    assert np.all(jumping(v) == [1, 2, 4, 5, 6])

    # test 2: random vector, naive counting
    v = np.random.randint(-100, 100, 1000)
    # patching 0 values
    v[v==0] = -1
    # naive way of counting jumps:
    positions = []
    for i in range(len(v)-1):
        if v[i] * v[i+1] < 0:
            positions.append(i)
            
    assert np.all(positions == jumping(v))

4. (1p) Generati o matrice aleatoare de dimensiune m*n care are m valori nan (not-an-number, https://numpy.org/doc/stable/reference/constants.html), la pozitii aleatoare. Determinati apoi suma elementelor non-nan din matrice in doua feluri (construiti doua functii). Comparati sumele returnate.

Exemplu:
```python
a = get_matrix(3, 4)
# sa presupunem ca a este
a = 
    1.5 2.2 np.nan
    4.3 np.nan np.nan
    10.1 5.0 -3.1
```

Suma elementelor este 20.0.
Indicatii: folositi functia `np.random.choice` cu parametri adecvati pentru a alege indici in mod aleator, fara repetare. 

In [4]:
import numpy as np
from random import sample as rand_sample

def get_matrix(m:int, n:int) -> np.ndarray:
    """i create a matrix of size m, n filled with elements from -10 to 10 randomly.
    i then add m indexes from 0 to len(matrix) to a tuple, indexes which will hold nan values.
    after that i loop through the tuple of indexes and set the values of the matrix to nan"""
    matrix: np.ndarray=np.random.uniform(low=-10, high=10, size=(m, n)).round(1)
    print(matrix)
    
    indexes_to_nan: tuple=tuple(rand_sample(range(m*n), m))
    print(indexes_to_nan)
    for i in range(0, len(indexes_to_nan)):
        matrix[indexes_to_nan[i]//n][indexes_to_nan[i]%n]=np.nan
    print(matrix)
    
    assert np.sum(np.isnan(matrix)) == m 
    return matrix

def sum_1(matrix:np.ndarray)->float:
    """returns the sum of all elements in the matrix but the nan ones are treated as 0"""
    return np.nansum(matrix)

def sum_2(matrix:np.ndarray)->float:
    """returns the sum of the elements of the matrix that are not nan."""
    return np.sum(matrix[~np.isnan(matrix)])

def naive_sum(a: np.ndarray) -> float:
    """cpp style sum*"""
    s = 0
    m, n = a.shape
    for i in range(m):
        for j in range(n):
            s += a[i, j] if not np.isnan(a[i, j]) else 0
    return s

if __name__ == '__main__':
    m, n = 3, 5
    a = get_matrix(m, n)
    sum1= sum_1(a)
    sum2 = sum_2(a)
    naiveSum = naive_sum(a)
    print("sum1:", sum1, "sum2:", sum2, "naiveSum:", naiveSum)
    assert np.allclose(sum1, naiveSum)
    assert np.allclose(sum2, naiveSum)
    # for students: why is it needed to use allclose and not == ?
    # allclose verifies if the two values are close to each other, while '==' verifies if they are equal

[[ 4.7  4.8  9.4  6.   1.5]
 [ 7.7  3.4  1.7 -0.5 -7.4]
 [-8.8 -4.5  5.3  9.6  3.2]]
(7, 9, 6)
[[ 4.7  4.8  9.4  6.   1.5]
 [ 7.7  nan  nan -0.5  nan]
 [-8.8 -4.5  5.3  9.6  3.2]]
sum1: 38.4 sum2: 38.4 naiveSum: 38.400000000000006


5. (1p) Folosnd functia `np.convolve`, sa se determine media alunecatoare (moving average) pentru un vector de 10000 de numere aleatoare; lungimea ferestrei alunecatore se da ca parametru al functiei construite de voi. Comparati rezultatele si viteza de executie cu a functiaie `naive_moving_average`.

Referinte:
1. [Moving average](https://en.wikipedia.org/wiki/Moving_average)
1. [np.convolve: How to Use Numpy convolve() Method](https://appdividend.com/2022/10/14/np-convolve/)

In [5]:
import numpy as np

def moving_average_fast(x:np.array, w:int)->np.array:
    """returns the moving average of x, with window size w. x will tend to 0"""
    assert x.ndim == 1, 'One dimension numpy array'
    assert w > 1, 'Average of at least two values'
    return np.convolve(x, np.ones(w), 'valid') / w

def moving_average_slow(x:np.array, w:int)->np.array:
    """same operation but done in a loop"""
    assert x.ndim == 1, 'One dimension numpy array'
    assert w > 1, 'Average of at least two values'
    result:np.array = np.zeros(x.shape[0]-w+1)
    for i in range(x.shape[0]-w+1):
        result[i] = np.mean(x[i:i+w])
    return result

if __name__ == '__main__':
    len_vec, w = 10000, 10
    x:np.array = np.random.rand(len_vec)

    a:np.array = moving_average_fast(x, w)
    b:np.array = moving_average_slow(x, w)

    assert len(a) == len(b), 'The two methods should return vectors of the same lengths'
    assert np.allclose(a, b), 'The two methods should return close vectors'

    %timeit moving_average_fast(x, w)
    %timeit moving_average_slow(x, w)

45.6 µs ± 1.1 µs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)
64.5 ms ± 1.65 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


6. (1p) Se dau vectorii de valori $x=[x_0 \dots x_{n-1}]$, $t=[t_0, \dots t_n-1]$, cu $t[0] < t[1] < \dots$. Sa se calculeze intr-o maniera vectorizata vectorul $v$ ale carui componente sunt:
$$
v[i] = \frac{x[i+1] - x[i]}{t[i+1] - t[i]}
$$

In prealabil sa se verifice (vectorizat sau functii NumPy) ca vectorul $t$ este format doar din valori strict crescatoare. Comparati rezultatele si viteza de executie cu o implementare care construieste vectorul $v$ pas cu pas.

Optional: incercati si o implementare folosind Numba. 

In [6]:
import numpy as np
from numba import jit

@jit
def is_increasing(t: np.array) -> bool:
    """function checks if the array given as parameter is increasing. np.all() returns true if all elements of the array are true.
    np.diff() returns the difference between the elements of the array. 
    ex: for [1, -3, 5, 6, 6] np.diff() returns [-4, 8, 1, 0]"""
    return np.all(np.diff(t) > 0)
    # return (np.all(i<j for i, j in zip(t, t[1:])))==True      ###!!!its not functioneaza i dont stiu why

@jit
def fast_v(x: np.array, t:np.array)->np.array:
    """usual function of assigning values to an array based on the values of other arrays using a loop.
    @jit however changes how the function is executed, making it faster than the usual pythonic way (only works with numpy arrays and loops).
    it is usually recommended to let @jit do its job without changing its parameters"""
    assert is_increasing(t), 'non increasing values'
    v: list=[]
    for i in range(1, len(x)):
        v.append((x[i]-x[i-1])//(t[i]-t[i-1]))
    return np.array(v)

def slow_v(x: np.array, t: np.array)->np.array:
    """same function as fast_v() but the decorator @jit is not used"""
    assert is_increasing(t), 'non increasing values'
    v: list=[]
    for i in range(1, len(x)):
        v.append((x[i]-x[i-1])//(t[i]-t[i-1]))
    return np.array(v)

if __name__ == '__main__':
    
    n:int = 100000
    x:np.array = np.random.rand(n)
    t:np.array = np.random.randint(1, 10, n)
    t:np.array = t.cumsum()
    assert is_increasing(t), 't should be an increasing vector'
    
    v1:np.array = fast_v(x, t)
    v2:np.array = slow_v(x, t)
    assert v1.shape == v2.shape
    assert np.allclose(v1, v2)

    %timeit fast_v(x, t)
    %timeit slow_v(x, t)
    

1.17 ms ± 40.5 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
70.5 ms ± 781 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


7. (2p) Se da o matrice $a$ cu numere reale. 
    1. Sa se calculeze o alta matrice $b$ care are valorile calculate astfel:
    $$
    b[i, j] = \frac{a[i, j] - MIN}{MAX-MIN}
    $$
    unde $MAX$ si $MIN$ sunt valoarile minima, respectiv maxima din $a$. Tranformarea se face printr-o functie care preia o matrice si returneaza un tuplu compus din matricea $b$ si valorile $MIN$ si $MAX$ 
    2. Verificati ca in urma acestei transformari matricea $b$ are valorile in intervalul $(-epsilon, 1+epsilon)$, unde $epsilon=1e-5$.
    3. Daca se dau $b$, $MIN$, $MAX$, care este transfomarea inversa prin care obtinem matricea $a$ originara? Verificati ca valorile lui $a$ si $a_{reconstituit}$ sunt aproximativ egale. 

In [7]:
import numpy as np
# from numba import jit

def min_max_scale(a: np.ndarray)->tuple():
    """finds the min and max of 'a'. creates 'b', scaled between 0 and 1 based on 'a' and returns a tuple of 'b', min(a) and max(a)."""
    minimum, maximum=a.min(), a.max()
    b=(a-minimum)/(maximum-minimum)
    return b, minimum, maximum

def check_scaling(y: np.ndarray, eps: float = 1e-5)->bool:
    """returns true if the elems of the array are between 0 and 1"""
    assert eps > 0
    return -eps < y.min() and y.max() < eps + 1

def inverse_min_max_scale(y: np.ndarray, MIN: float, MAX: float):
    assert MAX > MIN
    return y * (MAX - MIN) + MIN

if __name__ =='__main__':
    m, n = 100, 200
    a = np.random.randn(m, n)
    print(a, "\n\n")
    assert check_scaling(min_max_scale(a)[0])
    b, MIN, MAX = min_max_scale(a)
    print(b)
    assert np.allclose(a, inverse_min_max_scale(b, MIN, MAX))

[[-0.52838342  0.59222796 -1.2480686  ...  0.77766507 -1.14501967
  -0.65204948]
 [ 1.31708269  1.58993977 -0.42608152 ... -3.07803204 -1.67070125
   1.264825  ]
 [-0.72295785 -1.37132649 -1.80671171 ... -0.38074706 -0.88618744
  -1.82160518]
 ...
 [ 0.1362522  -0.69060256  0.40383346 ...  1.00568727  0.58586532
  -0.67148753]
 [-1.25262097  0.95814327 -0.00337824 ... -0.68708436  2.05265824
   0.44767678]
 [-0.22802746  0.4521886   0.11012297 ... -0.25103675  0.236781
   0.8465719 ]] 


[[0.43845802 0.59102606 0.34047494 ... 0.61627279 0.35450476 0.42162124]
 [0.68971296 0.72686167 0.45238613 ... 0.09133066 0.28293472 0.68259822]
 [0.41196727 0.32369374 0.26441728 ... 0.45855829 0.38974403 0.26238958]
 ...
 [0.52894626 0.41637235 0.56537669 ... 0.64731736 0.5901598  0.41897481]
 [0.33985515 0.64084438 0.50993598 ... 0.41685134 0.78985946 0.57134583]
 [0.47935063 0.5719601  0.52538884 ... 0.47621798 0.54263297 0.62565426]]
