### Contains

1. Exercises with functions
1. Exercises with Numpy

## Exercises with functions:

 1. Write a function that receives as parameter a number of 5 digits. Return a list of all prime numbers made of the digits of the parameter.

In [1]:
from typing import List
from itertools import permutations


def isPrime(number: int) -> bool:
    if number <= 1:
        return False
    elif number == 2 or number == 3:
        return True
    elif number % 2 == 0 or number % 3 == 0:
        return False
    else:
        for d in range(5, int(number**0.5)+1, 6):
            if number % d == 0 or number % (d+2) == 0:
                return False
    return True


def all_prime_with_5_digits(number: int) -> bool:
    """turns a number into a list of digits, then generates all permutations of the digits, then for every permutation it checks if the number made from it is prime"""
    #maybe check if the number has 5 digits maybe?
    primes_list: List[int] = []
    digit_list: List[str] = []
    for i in str(number):
        digit_list.append(i)
    perm_of_all_digits: List[str] = list(permutations(digit_list))
    for set_of_digits in perm_of_all_digits:
        number = 0
        for digit in set_of_digits:
            number = number*10+int(digit)
        if isPrime(number):
            primes_list.append(number)
    print(primes_list)


all_prime_with_5_digits(13579)


[13597, 13759, 15739, 15937, 15973, 17359, 17539, 19753, 31957, 37159, 37591, 37951, 39157, 51973, 53197, 53719, 53791, 53917, 57139, 57193, 71359, 71593, 73951, 75193, 75391, 75913, 75931, 79153, 79531, 91573, 91753, 95317, 95713, 95731]


2. Write a function that takes as parameter a phrase of maximum 12 words and returns a tuple which contains only the palindrome words. 

In [2]:
import string
from typing import List


def is_palindrome(word: str) -> bool:
    #return word == reversed(word)  #this doesn't work
    return word == word[::-1]


def return_palindrome_words(phrase: str) -> List[str]:
    """function that returns a list of all the palindrome words in a phrase"""
    #maybe try to check for punctuation and remove it maybe maybe
    word_list: List[str] = phrase.split()
    palindrome_word_list: tuple = ()
    for word in word_list:
        if is_palindrome(word):
            palindrome_word_list += (word,)

    return palindrome_word_list


palindrome_word_list: List[str] = return_palindrome_words(
    "madam level eye your mom gae. today issa goog day")
print(palindrome_word_list)


('madam', 'level', 'eye', 'mom', 'goog')


3. Define a function that takes as parameter a sentence (string or list). Return a tuple of the next: the number of consonants, number of vowels and the number of digits from the given parameter. verify if the sum of the 3 make a perfect square.

In [3]:
from typing import Tuple


def vowels_consonants_and_digits(phrase: str) -> Tuple[int, int, int]:
    """the function uses a list of words (if string make it list) and goes through 
    the list to count the vowels, consonants and digits."""
    word_list: List[str] = phrase.split() if type(phrase) == str else phrase
    vowConDig: Tuple[int, int, int] = (0, 0, 0)
    for word in word_list:
        for char in word:
            if char in "aeiouAEIOU":
                vowConDig = (vowConDig[0]+1, vowConDig[1], vowConDig[2])
            elif char.isalpha():
                vowConDig = (vowConDig[0], vowConDig[1]+1, vowConDig[2])
            elif char.isdigit():
                vowConDig = (vowConDig[0], vowConDig[1], vowConDig[2]+1)
    return vowConDig


vowConDig: Tuple[int, int, int] = vowels_consonants_and_digits(
    "sometimes you have to lose yourself first in order to find yourself later... 123")
print(vowConDig)
sumOfVowConDig: int = vowConDig[0]+vowConDig[1]+vowConDig[2]
print("sum of vowels, consonants and digits is:", sumOfVowConDig)
if sumOfVowConDig**0.5 == int(sumOfVowConDig**0.5):
    print("the sum of the vowels, consonants and digits is a perfect square")
else:
    print("the sum of the vowels, consonants and digits is NOT a perfect square")

(25, 36, 3)
sum of vowels, consonants and digits is: 64
the sum of the vowels, consonants and digits is a perfect square


4. Write a recursive function that determines if a number can be broken down into a sum of consecutive numbers

In [4]:
def is_sum_of_consec_nbs(number: int, a: int, sumOfConsec: int):
    """recursive function that checks if a number can be the sum of some consecutive numbers.
    unless 'number' is odd (->it surely can be sum of two consec nbs) recursively increase 'a' and 'sumOfConsec'
    form: a + (a+1) + (a+2) + (a+3) + (a+4) + (a+5) + (a+6) + (a+7) + (a+8).
    a=    1     2       3       4       5       6       7       8       9 
    soc=  0     1       3       6       10      15      21      28      36
    ex: 'number'=38 gets to 'a'=4 and 'sumOfConsec'=6 ==> a + (a+1) + (a+2) + (a+3) = 4a+6
    ==> 4a+6=38 ==> 4a=38-6 ==> 4a=32 ==> a=8 ==> 8+9+10+11=38"""
    if int(number % 2) != 0:
        print(number//2, "+", number//2+1, "=", number)
        return True
    elif int(number-sumOfConsec) % a == 0:
        for i in range(0, a):
            print((number-sumOfConsec)//a + i, "+", end=" ")
        print("\b\b=", number)
        return True
    elif sumOfConsec+a > number:
        print("the number cannot be a sum of consec numbers")
        return False
    is_sum_of_consec_nbs(number, a+1, sumOfConsec+a)


if __name__ == "__main__":
    a: int = 2
    sumOfConsec: int = 1
    isTru: bool = is_sum_of_consec_nbs(int(18), a, sumOfConsec)

{  # iterative version
    # def can_split_in_sum_of_consec(number: int) -> bool:
    #     """this function goes as follows: if the number is odd it surely can be a sum of consecutive nbs. else it goes by
    #     the formula n+(n+1)+(n+2)+... with every iteration until the "side" sum is bigger than the number. if the number
    #     minus the "side" sum is a multiple of "n" then we found the first elem of the sequence and we can return True
    #     ex: for 46 we have n+(n+1)+(n+2)+(n+3). 4n+6=46. 4n=46-6. 4n=40 n=10. 10+11+12+13=46."""
    #     #maybe try to make it recursive maybe?
    #
    #     if number % 2 != 0:
    #         print(number//2, "+", number//2+1, "=", number)
    #         return True
    #     sumOfConsec: int = 1
    #     a: int = 2
    #     while sumOfConsec+a < number:
    #         if (number-sumOfConsec) % a == 0:
    #             for i in range(0, a):
    #                 print((number-sumOfConsec)//a + i, "+", end=" ")
    #             print("\b\b=", number)
    #             return True
    #         sumOfConsec += a
    #         a += 1
    #     print("the number cannot be a sum of consec numbers")
    #     return False

    # can_split_in_sum_of_consec(44)
}


5 + 6 + 7 = 18


{}

## Numpy exercises

1. A NumPy vector is given. Determine the list of unique elements. Make a square matrix of dimension `len(v)/2` that contains the unique elements of the vector.
Complete with gcd of the unique elements the empty positions of the matrix.

In [5]:
import numpy as np
from typing import List

def gcd(a: int, b: int) -> int:
    #orig version: return a if b == 0 else gcd(b, a % b)
    """euclidean algorithm"""
    while b:
        a, b = b, a % b
    return a
def find_gcd_of_arr(arr: np.ndarray) -> int:
    gcd_of_arr: int = int(arr[0])
    for i in range(1, len(arr)):
        gcd_of_arr = gcd(gcd_of_arr, arr[i])
    return gcd_of_arr

def expand_list_with_gcd_of_elems(unique_elem_list: np.ndarray, size_of_matrix: int) -> np.ndarray:
    """given a perfect square number, expand the list with the gcd of the elements to the size of that number"""
    gcd_of_unique_elem_list: int = find_gcd_of_arr(unique_elem_list)
    for i in range(unique_elem_list.size, size_of_matrix):
        unique_elem_list = np.append(unique_elem_list, gcd_of_unique_elem_list)
    return unique_elem_list


def is_square_root(number: float) -> bool:
    return True if number**0.5 == int(number**0.5) else False
def get_size_of_square_matrix(number: int) -> int:
    """gets the next perfect square number"""
    if (is_square_root(number) == False):
        number = number+1
        while (is_square_root(number) == False):
            number += 1
    return int(number**0.5)


def create_matrix_of_size_square_root(size_of_unique_elem_list: int) -> List[List[int]]:
    """takes the length of the unique_elem_list and creates a matrix of size greater than or equal to that length
    (the size has to be square root because the matrix is a square)"""
    size_of_matrix: int = get_size_of_square_matrix(size_of_unique_elem_list)
    matrix_of_unique_elem: np.ndarray = np.zeros(shape=(size_of_matrix, size_of_matrix), dtype=int)
    return matrix_of_unique_elem


def make_list_of_unique_elem(arr: np.ndarray) -> np.ndarray:
    """goes through every elem of the array and if it appears only once (its unique) it gets 
    added to the list of unique elems, otherwise it gets to the list of non-unique ones"""
    unique_elem_list: np.ndarray = np.array([])
    not_unique_elem_list: np.ndarray = np.array([])
    for i in range(0, len(arr)):
        if arr[i] not in not_unique_elem_list:
            elemIsUnique: bool = True
            for ii in range(i+1, len(arr)):
                if arr[i] == arr[ii]:
                    elemIsUnique = False
                    break
            if elemIsUnique:
                unique_elem_list = np.append(unique_elem_list, arr[i])
            else:
                not_unique_elem_list = np.append(not_unique_elem_list, arr[i])
    return unique_elem_list


if __name__ == "__main__":
    arr: np.ndarray = np.array([28, 2, 2, 4, 12, 6, 2, 6, 16, 100, 2])
    unique_elem_list: np.ndarray = make_list_of_unique_elem(arr)

    matrix_of_unique_elems: np.ndarray = create_matrix_of_size_square_root(unique_elem_list.size)

    unique_elem_list = expand_list_with_gcd_of_elems(unique_elem_list, matrix_of_unique_elems.size)
    print(unique_elem_list)

    matrix_of_unique_elem = unique_elem_list.reshape(matrix_of_unique_elems.shape)
    print(matrix_of_unique_elem)


[ 28.   4.  12.  16. 100.   4.   4.   4.   4.]
[[ 28.   4.  12.]
 [ 16. 100.   4.]
 [  4.   4.   4.]]


2. ...

3. For a matrix of numbers determine the sum between the min and max of elements from each row or each column, based on the value of a parameter of type boolean `compute_on_columns`.

In [6]:
import numpy as np
import random

def sum_of_min_max_lines_or_collumns(matrix, compute_on_column:bool) -> None:
    """computes the sum of the min and max of: if compute_on_column is True, every column, otherwise every line
    (but negated in the expression because shape[0] means rows but axis=0 means collumns so axis=1 means rows).
    # amin"""
    print("compute_on_column is:", compute_on_column)
    sum_of_min_max=np.amin(matrix, axis=int(not compute_on_column)) + np.amax(matrix, axis=int(not compute_on_column))
    print(sum_of_min_max.sum())
    
    print("\naxis=0 =>")
    min=np.amin(matrix, axis=0)
    max=np.amax(matrix, axis=0)
    print("min=", min, "\n","max=", max)
    print("axis=1 =>")
    min=np.amin(matrix, axis=1)
    max=np.amax(matrix, axis=1)
    print("min=", min, "\n","max=", max)

def main() -> None:
    matrix=np.full(shape=(3,4), fill_value=0, dtype=int)
    for i in range(0, matrix.shape[0]):
        for j in range(0, matrix.shape[1]):
            matrix[i,j]=random.randrange(0, 100)
    print(matrix)
    sum_of_min_max_lines_or_collumns(matrix, random.choice([True, False]))
main()

[[35 90 42 22]
 [62 64 96 82]
 [88 60 38  5]]
compute_on_column is: False
363

axis=0 =>
min= [35 60 38  5] 
 max= [88 90 96 82]
axis=1 =>
min= [22 62  5] 
 max= [90 96 88]


4. For a number given as input from keybaord, detemine a square matrix of random elements in the interval `[0, 2n]`. Calculate the min of elements from the main diagonal and the max of elements from the secondary diagonal. Return the sum of the 2 values.

In [7]:
import random
import numpy as np


def main():
    """generates a square matrix of defined size and every elem is a random nb from 0 until up to 2*n
    then traverses the main diagonal for the smallest elem in there and the secondary diagonal for the biggest elem in there"""
    #i made everything in main ik ik
    n: int = input("n:")
    while (not n.isnumeric()):
        n = input("n needs to be a number. try again:")
    matrix: np.ndarray[int] = np.array(
        [[random.randrange(0, 2*int(n)+1) for i in range(4)] for j in range(4)])
    matrix = matrix.reshape(4, 4)
    print(matrix)

    min: int = matrix[0, 0]
    for i in range(matrix.shape[0]):
        if (matrix[i, i] < min):
            min = matrix[i, i]
    max: int = matrix[0, matrix.shape[1]-1]
    for (i, j) in zip(range(matrix.shape[0]), range(matrix.shape[1]-1, -1, -1)):
        if (matrix[i, j] > max):
            max = matrix[i, j]
    return (min, max)


min_max: tuple[int, int] = main()
print(min_max)


[[ 7  3  4  1]
 [ 2 10  8  5]
 [ 0  2  1  4]
 [ 1  8 10 10]]
(1, 8)


5. Download the Wine dataset from 'http://archive.ics.uci.edu/ml/datasets/Wine', the file `wine.data`, and upload it into a Numpy matrix using `np.genfromtxt`. Pick 28 random positions from the matrix, set the positions to `nan`, create a function which, given a matrix, returns a colection of indexes of rows and columns in which `nan` values are located, as well as the "fixed" matrix: the values `nan` are replaced with a value given as parameter.

In [8]:
from cmath import nan
import numpy as np
import random

def turn_nan_positions_to_value(matrix: np.ndarray, value: int):
    """goes through every elem of the matrix, finds the nans, remembers the indexes of the nan positions 
    in a list, changes the nans into a given value and returns the list of changed indexes."""
    list_of_indexes_changed: List[Tuple]=[]
    for i in range(matrix.shape[0]):
        for j in range(matrix.shape[1]):
            if np.isnan(matrix[i, j]):
                list_of_indexes_changed.append((i, j))
                matrix[i, j]=value
    print(list_of_indexes_changed)
    return list_of_indexes_changed
            

def turn_random_positions_to_nan(matrix, numberOfPositions):
    """turns a given number of positions in the matrix to nans. the positions are chosen randomly"""
    for counter in range(0, numberOfPositions):
        i=random.randrange(0, matrix.shape[0])
        j=random.randrange(0, matrix.shape[1])
        matrix[i, j]=nan

def main():
    matrix: np.ndarray=np.genfromtxt('files\wine.data', delimiter=',')
    print(matrix)
    turn_random_positions_to_nan(matrix, 28)
    turn_nan_positions_to_value(matrix, 0)  #return to where..
    
if __name__ == "__main__":
    main()

[[1.000e+00 1.423e+01 1.710e+00 ... 1.040e+00 3.920e+00 1.065e+03]
 [1.000e+00 1.320e+01 1.780e+00 ... 1.050e+00 3.400e+00 1.050e+03]
 [1.000e+00 1.316e+01 2.360e+00 ... 1.030e+00 3.170e+00 1.185e+03]
 ...
 [3.000e+00 1.327e+01 4.280e+00 ... 5.900e-01 1.560e+00 8.350e+02]
 [3.000e+00 1.317e+01 2.590e+00 ... 6.000e-01 1.620e+00 8.400e+02]
 [3.000e+00 1.413e+01 4.100e+00 ... 6.100e-01 1.600e+00 5.600e+02]]
[(6, 6), (13, 4), (17, 9), (22, 0), (22, 9), (34, 0), (41, 11), (44, 3), (44, 7), (45, 3), (48, 2), (52, 6), (52, 12), (66, 5), (75, 6), (79, 3), (82, 10), (85, 9), (86, 10), (93, 2), (108, 5), (127, 9), (130, 11), (133, 12), (134, 10), (154, 2), (154, 9), (155, 11)]
